### ISSUE TITLE
Set fixed screensize

### ISSUE THREAD

**Issue by linzjax** [Cadasta/cadasta-test#21]
Certain elements are out of view at different screen sizes. To prevent conflicts when switching from screen size to screen size, we should run set_window_size at the beginning of each test for consistency.

**Comment by shailysangwan** [comment]
I just noticed that the Edit Relationship button does not work unless the window is a certain size.
As seen in this screencast, the button only works if clicked above a certain point.
For selenium, this button is not clickable at all.

/home/anukul/media/Screencast_03-24-2017_05:40:52 AM.webm

So, should we set the window size to a static value, or maximize it?

**Comment by shailysangwan** [comment]
+1
I just noticed that clicking the Edit relationships button does not work properly below a certain width.
For Selenium, the button is not clickable.

![screencast-from-03-24-2017-05_54_05-am](https://cloud.githubusercontent.com/assets/22165016/24275642/fcb737b0-1056-11e7-98a9-3a81164b69f8.gif)

Should we set the window size to a static value, or maximize it?

**Comment by clash99** [comment]
That is a bug that I can fix but I would suggest setting the width to something like 1100 or 1200 pixels wide if possible.

**Comment by clash99** [comment]
Overlap issue fixed in PR #1343.

**Comment by linzjax** [comment]
The PR for this did not solve the problem (The screen sizes adjusts down and then back up, see gif), and it introduced an error in python3 because it inconsistently used tabs instead of spaces. Is the screen size adjustment just a problem with python3? Did the screen stay the correct size when you tested it before merging it in?

I would suggest (in addition to making sure screen size is consistent) finding a way to ensure that the button you are trying to access is either already on the screen, or that the window scrolls down to it before trying to click on it. Take a look at the `click_through` function in the [old functional tests](https://github.com/Cadasta/cadasta-platform/blob/master/functional_tests/base.py#L118-L132). It might also help address issue #22 the clicks getting ahead of themselves.

![screen_resizing_glitch](https://cloud.githubusercontent.com/assets/8128188/24418135/f603cfa4-13b8-11e7-92a3-7ceb61bba933.gif)

**Comment by shailysangwan** [comment]
I'm not sure as to what's going wrong in the GIF.
The window is at a particular size when firefox starts, it sizes down, but then sizes back up to 1920x1080 before the URL is loaded, right?
If I had to make a guess, then it's probably sizing down due to what's going on in the Firefox webdriver's constructor.
After the base class's constructor exits, a call to `set_window_size` size is made, and the window size changes to 1920x1080.
I think this is in line with the expected behavior. Please correct me if I'm wrong.

To ensure that the button we want to click on is indeed clickable, we can use `ActionChains` to move to the respective element before issuing a click event.
Should we do this for all clicks? This will require changes to the `CustomWebDriver` class to avoid duplication of code.

**Comment by linzjax** [comment]
Ah I see what the problem is, you have a much bigger monitor than me 😂 It's trying to size up to the correct size, but it's getting anywhere close (mine maxes out at 1280 x 800). Maybe we could set the size to something smaller (maybe 1024 x 768) as clash suggested. My apologies for misdiagnosing the issue.

The other thing is that the action chain doesn't seem to be working correctly.
`action.send_keys(Keys.TAB).send_keys(Keys.RETURN).perform()` types in "Return" as a string in the full_name input. Unfortunately, I haven't the foggiest idea of why it's doing this, but I would say we should either refactor the ActionChain, or find a different way of handling clicks (i.e. `click_through` function in the [old functional tests](https://github.com/Cadasta/cadasta-platform/blob/master/functional_tests/base.py#L118-L132).

<img width="1280" alt="screen shot 2017-03-29 at 9 28 50 am" src="https://cloud.githubusercontent.com/assets/8128188/24458421/e0bcdf74-1466-11e7-82f9-90a6ec5fc646.png">

**Comment by shailysangwan** [comment]
@linzjax Should I just set it to `maximize_window()`?

As for the ActionChain, does `Keys.ENTER` work for you?
I googled this, and there was another instance of `Keys.RETURN` not working on OSX.

**Comment by shailysangwan** [comment]
@linzjax Should I just set it to `maximize_window()`?

As for the `ActionChains` issue, can you try with `Keys.ENTER` instead? I googled this, and found another instance of `Keys.RETURN` not working on OSX.

Either way, I was suggesting that we use `ActionChains` only to scroll elements into view.
We can use the normal `WebElement.click()` with an appropriate XPath for clicking on elements.

**Comment by seav** [comment]
The current test suite now sets the screen size [here](https://github.com/Cadasta/cadasta-test/blob/master/cadasta/test/webdriver.py#L25) and this works in both local testing and using BrowserStack.
